# Generated by Django 3.1.6 on 2021-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210207_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='title',
        ),
    ]
